### ISSUE TITLE
The tonce xxx has already been used by access_key yyy

### ISSUE THREAD

**Issue by abitmore** [peatio/peatio-client-ruby#2]
Race conditions while running multiple instances (multiple processes) of client (with same account but doing different tasks).

**Comment by janx** [comment]
This is a problem with Peatio instead of the client, will fix there.

**Comment by janx** [comment]
fixed by https://github.com/peatio/peatio/commit/0f032ce0d624f7668163a8ef4d740a47bea9b2d4
